### PR TITLE
changed the GPIO code to use bit-banding

### PR DESCRIPTION
**Pull request by theotherjimmy**
please test in Keil! I'm using stddef.h.

### CODE REVIEW

**Comment by geky** [comment]
Excellent, looks good, can't test it on Keil anymore but I can't see how if could break on windows...

**Comment by geky** [comment]
@KGilbert1993, does this mean it was tested in windows? If so I don't see any reason to not merge. : D

**Comment by geky** [comment]
fixes #48

**Comment by KGilbert1993** [comment]
It worked in Kiel for me, go for it!

**Pull request merged**
